services = "../Temporary_data/All_ES_data_classif_env_corr_regionTRUE_scale_withinTRUE.csv"
services_ignore = ["Region", "LU", "Classif", "Classif2"]




environments = "../Temporary_data/environments_new.csv"
environments_ignore = ["Region", "LU"]

environments_pca = "../Temporary_data/environments_pca.csv"
plant_abundances = "../Temporary_data/Plants_abundance.csv"
bird_abundances = "../Temporary_data/Birds_abundance.csv"
fungi_abundances = "../Temporary_data/Fungi_abundance.csv" 
bird_charism_abundances = "../Temporary_data/Birds_charism_abundance.csv" 


scenario = "../Temporary_data/scenarios_by_regionTRUE_constrainedFALSE.csv"
max_tentative = 100
replica = 200

logfile = "../Temporary_data/output_env_corr_regionTRUE.log"
output_picked = "../Temporary_data/picked_env_corr_regionTRUE.csv.gz"
output_landscapes = "../Temporary_data/landscapes_env_corr_regionTRUE.csv.gz"
